### ISSUE TITLE
Parker: Describe local computer setup

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/CounterProject#16]
Which operating system: Windows/Mac/Linux?
What tools do you use for coding?

**Comment by Arcaderat** [comment]
Usually for coding I'm on Linux, but I also have Windows available. Most recently for coding in Python, I've been using PyCharm, but I'd say I'm still fairly new to it, and I'm not particularly attached to it if there's another tool you think would be better.

**Comment by ashepherd** [comment]
ok cool! Feel free to use whatever OS and IDE that's most comfortable to you! Just wanted to know so we could best help you with questions/issues when they arise. Feel free to close this Issue and move it to the `Done` bucket when you are ready.
