### ISSUE TITLE
Review Managing Google Service Account Keys

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/CounterProject#24]
https://cloud.google.com/iam/docs/understanding-service-accounts#managing_service_account_keys

To ensure we don't do anything innsecure

**Comment by Arcaderat** [comment]
It looks like the most important thing they stress is keeping the service key out of source code and repository. It also says to consider having a unique service account for each service to limit permissions, and to consider periodically rotating the keys. I'll make sure to be careful about not committing the service key, but I think the other things are up to @ashepherd to decide as the admin.

**Comment by ashepherd** [comment]
Thanks Parker! I deleted the Slack messages that shared these private details.

**Comment by ashepherd** [comment]
@ashepherd will get the JSON and access keys to Parker

**Comment by ashepherd** [comment]
sent JSON for the dataset statistic counter service key to @Arcaderat on Slack
