### ISSUE TITLE
Share Custom Reports w/ Parker

### ISSUE THREAD

**Issue by Arcaderat** [BCODMO/CounterProject#25]
We talked about doing this so I could have easy access to the relevant data on the dashboard, but didn't see how at the time.

Sharing Custom Reports:
1. Find the report under Customization -> Custom Reports
2. In the actions button by the report there's a share option
3. Share Template Link generates a URL to send

**Comment by ashepherd** [comment]
@Arcaderat here's the custom report template links

| Report | Template Link | Statistic Type |
|--|--|--|
| Map It Button Click | https://analytics.google.com/analytics/web/template?uid=mX2-UqfySTagvf1ADDj4eg | Download |
| Get Data Button Click | https://analytics.google.com/analytics/web/template?uid=exgfM0oXRmqs2drQzy_krQ | Download |
| Dataset ISO Click | https://analytics.google.com/analytics/web/template?uid=-oxQTpiuRRCZHuj9iex5mw | View |
| Dataset HTML Click | https://analytics.google.com/analytics/web/template?uid=Y9T2AKAnQ2CcMpcm29tM3g | View |
| Dataset JSON-LD Click | https://analytics.google.com/analytics/web/template?uid=J-b4D8pnRHyt-FBHCva4Ig | View |
| Dataset RDF Click | https://analytics.google.com/analytics/web/template?uid=xhRH4qXDSjulqJuZ5zfgtg | View |
| ERDDAP View Table | https://analytics.google.com/analytics/web/template?uid=Ppc1j1ZMQJaL6Db5lLFtXg | Download |
| ERDDAP Subset Data | https://analytics.google.com/analytics/web/template?uid=gtkyW1wQR-uLErLTODG6kQ | View |
| ERDDAP CSV Download | https://analytics.google.com/analytics/web/template?uid=JfmCbT-XSl6tv-IKwfxgpw | Download |
| ERDDAP TSV Download | https://analytics.google.com/analytics/web/template?uid=pTsbRbOATOOj-XFZxYVXLw | Download |
| ERDDAP GeoJSON Download | https://analytics.google.com/analytics/web/template?uid=jcDwAqfEQCKlOztSNOrrQA | Download |
| ERDDAP MATLAB Download | https://analytics.google.com/analytics/web/template?uid=pTsbRbOATOOj-XFZxYVXLw | Download |
| ERDDAP NetCDF Download | https://analytics.google.com/analytics/web/template?uid=W4XuE71sTBS_qPGwk9PtQg | Download |
| ERDDAP ODV Download | https://analytics.google.com/analytics/web/template?uid=AEyBENXDQKmYrk4z6wARzg | Download |
